# MCP Journal Configuration
# This file contains essential configuration options for the MCP Journal tool

# Journal settings
journal:
  # Base path for all journal files (relative to repo root)
  path: "sandbox-journal/"

# Git repository settings
git:
  # Files to exclude from analysis in journal entries
  exclude_patterns:
    - "journal/**"        # Ignore journal directory to prevent recursion
    - ".mcp-journalrc.yaml"  # Ignore config file itself

# Telemetry settings
telemetry:
  # Whether to collect telemetry
  enabled: false
